# Docker安装Server

version: '3'
services:
  xiaozhi-esp32-server:
    network_mode: host
    image: ghcr.nju.edu.cn/xinnan-tech/xiaozhi-esp32-server:server_latest
    container_name: xiaozhi-esp32-server
    command: sh -c "pip3 install -q apscheduler==3.10.4 paho-mqtt==2.1.0 'aiogram>=3,<4' 'aiohttp-socks>=0.8.4' && exec python app.py"
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Asia/Shanghai
    ports: []
      # ws服务端
      # - "8000:8000"
      # http服务的端口，用于简单OTA接口(单服务部署)，以及视觉分析接口
      # - "8003:8003"
    volumes:
      # 配置文件目录
      - ./data:/opt/xiaozhi-esp32-server/data
      # 插件与核心热修复
      # - ./core/connection.py:/opt/xiaozhi-esp32-server/core/connection.py
      # 模型文件挂接，很重要
      # - ./models/SenseVoiceSmall/model.pt:/opt/xiaozhi-esp32-server/models/SenseVoiceSmall/model.pt
      - ./models/snakers4_silero-vad:/opt/xiaozhi-esp32-server/models/snakers4_silero-vad
      - ./plugins_func:/opt/xiaozhi-esp32-server/plugins_func
      - ./core:/opt/xiaozhi-esp32-server/core
      - ./app.py:/opt/xiaozhi-esp32-server/app.py
